apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiles_inspire
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tiles_inspire
  template:
    metadata:
      labels:
        app: tiles_inspire
    spec:
      containers:
      - name: martin
        image: ghcr.io/maplibre/martin
        args:
        - "--auto-bounds"
        - "calc"
        - "--cache-size"
        - "2048"
        - "--keep-alive"
        - "200"
        - "--pool-size"
        - "20"
        - "--webui"
        - "disable"
        - "--default-srid"
        - "3763"
        - "--save-config"
        - "/tmp/config.yml"
        envFrom:
          - secretRef:
              name: app-secrets # The name of the Secret
        env:
          - name: DATABASE_URL
            valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REMOTE_INSPIRE_URL
          - name: WATCH_MODE
            value: "true"
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "host.docker.internal"
