---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pygeoapi
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: pygeoapi
          # We use this pygeoapi version by default.
          image: geopython/pygeoapi:0.23.4
          command:
            - bash
            - /etc/pygeoapi/entrypoint.sh

          envFrom:
            - secretRef:
                name: app-secrets # The name of the Secret

          env:
            # The pygeoapi config file expects these `SAMPLE_CONFIG_*`
            # environment variables to be set.

            - name: PYGEOAPI_OPENAPI_GENERATE_FAIL_ON_INVALID_COLLECTION
              value: "false"

            - name: CONTAINER_PORT
              value: "5000"

            - name: HOST_URL
              value: "https://k8.byteroad.net/"

            # We will use this configuration file ...
            - name: PYGEOAPI_CONFIG
              value: /etc/pygeoapi/pygeoapi-config.yaml

            # ... and this location for the auto-generated OpenAPI spec.
            - name: PYGEOAPI_OPENAPI
              value: /var/lib/pygeoapi/pygeoapi-openapi.yaml

          # The value of the URL of this pygeoapi deployment depends on where
          # it will be deployed to --- so we do not set it here. We will
          # override it later, in the target-dependent definitions.
          #
          # - name: SAMPLE_CONFIG_PYGEOAPI_URL
          #   value: https://example.comp

          ports:
            - name: http
              containerPort: 5000

          volumeMounts:
            - name: config
              mountPath: /etc/pygeoapi
              readOnly: true

            - name: config
              mountPath: /templates/_base.html
              subPath: _base.html

            - name: config
              mountPath: /templates/landing_page.html
              subPath: landing_page.html

            - name: config
              mountPath: /pygeoapi/pygeoapi/static/img/Logo_DGT.png
              subPath: Logo_DGT.png
              readOnly: true

            - name: tmp
              mountPath: /tmp

            - name: var
              mountPath: /var/lib/pygeoapi

          securityContext:
            readOnlyRootFilesystem: true

      volumes:
        - name: config
          configMap:
            name: pygeoapi-config
            items:
              - key: entrypoint.sh
                path: entrypoint.sh

              - key: pygeoapi-config.yaml
                path: pygeoapi-config.yaml

              - key: _base.html
                path: _base.html

              - key: landing_page.html
                path: landing_page.html
                
              - key: Logo_DGT.png
                path: Logo_DGT.png


        - name: tmp
          emptyDir:
            medium: Memory

        - name: var
          emptyDir:
            medium: Memory
