---
# The definition of the Kubernetes deployment object for the pygeoapi pods.
#
# The interesting details are in the `deployment.yaml` file and in the pygeoapi
# configuration file mentioned below.
resources:
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      app: tiles-scalargis