apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiles-caop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tiles-caop
  template:
    metadata:
      labels:
        app: tiles-caop
    spec:
      containers:
      - name: martin
        image: ghcr.io/maplibre/martin
        args:
        - "--auto-bounds"
        - "calc"
        - "--cache-size"
        - "2048"
        - "--keep-alive"
        - "200"
        - "--pool-size"
        - "20"
        - "--webui"
        - "disable"
        - "--default-srid"
        - "3763"
        - "--config"
        - "/config/config.yaml"
        envFrom:
          - secretRef:
              name: app-secrets # The name of the Secret
        env:
          - name: DATABASE_URL
            valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REMOTE_CAOP_URL
          - name: WATCH_MODE
            value: "true"

        volumeMounts:
          - name: config
            mountPath: /config/config.yaml
            subPath: config-caop.yaml
            readOnly: true

        securityContext:
          readOnlyRootFilesystem: true

      volumes:
              - name: config
                configMap:
                  name: caop-config

      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "host.docker.internal"

