apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiles-cos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tiles-cos
  template:
    metadata:
      labels:
        app: tiles-cos
    spec:
      containers:
      - name: martin
        image: ghcr.io/maplibre/martin
        args:
        # - "--auto-bounds"
        # - "calc"
        # - "--cache-size"
        # - "2048"
        # - "--keep-alive"
        # - "200"
        # - "--pool-size"
        # - "5"
        # - "--webui"
        # - "disable"
        # - "--default-srid"
        # - "3763"
        # - "--save-config"
        # - "/tmp/config.yml"
        - "--config"
        - "/config/config.yaml"
        envFrom:
          - secretRef:
              name: app-secrets # The name of the Secret
        env:
          - name: DATABASE_URL
            valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REMOTE_COS_URL
          - name: WATCH_MODE
            value: "true"

        volumeMounts:
          - name: config
            mountPath: /config/config.yaml
            subPath: config-cos.yaml
            readOnly: true

        securityContext:
          readOnlyRootFilesystem: true

      volumes:
              - name: config
                configMap:
                  name: cos-config

        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "host.docker.internal"
