apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-matomo-config
  namespace: ingress-nginx
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/nginx/access.log
      pos_file /var/log/fluentd-pos/nginx.pos
      tag nginx.access
      <parse>
        @type nginx
      </parse>
    </source>

    <match nginx.access>
      @type http
      endpoint "#{ENV['MATOMO_URL']}/matomo.php?idsite=#{ENV['MATOMO_SITE_ID']}&rec=1&apiv=1&action_name=Nginx%20Log&url=http%3A%2F%2F${record['host']}${record['path']}&token_auth=#{ENV['MATOMO_TOKEN']}&cip=${record['remote']}&ua=${record['agent']}"
      tls_verify_mode none
      <format>
        @type json
      </format>
      <buffer>
        flush_interval 10s
      </buffer>
    </match>