---
# Sample pygeo deployments are built from these pieces --- look into their
# respective entries under this directory for more information
resources:
  - pygeoapi
  - tiles-caop
  - tiles-inspire
  # - ingress.yaml
  - ingress-ssl.yaml
